NHAXE/NHAXE/NHAXE/Controllers/KhachHangController.cs
using Models;
using Models.DAO;
using Models.Framework;
using NHAXE.Areas.Admin.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NHAXE.Controllers
{
    public class KhachHangController : Controller
    {
        // GET: KhachHang
        public ActionResult Index()
        {

            return View();
        }

        // GET: KhachHang/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: KhachHang/Create
        public ActionResult Create()
        {
            return View();
        }
        

        // POST: KhachHang/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(KHACH_HANG KH)
        {
            try
            {
                KH.MATKHAU = Encryptor.MD5Hash(KH.MATKHAU);
                KH.CONFIRM_PASS = Encryptor.MD5Hash(KH.CONFIRM_PASS);
                if (ModelState.IsValid)
                {
                    var m = new KHACH_HANG_DAO().TimEmailKH(KH.EMAIL_KH);
                    if (m == null)
                    {
                        var model = new KHACH_HANG_DAO();
                    string res = model.AddKhachHang(KH);
                    if (res != null)
                            ModelState.AddModelError("", "Đăng kí thành công");
                        else
                    {
                        ModelState.AddModelError("", "Không thêm được dữ liệu");
                    }
                }
                    else
                    { ModelState.AddModelError("", "Email đã sử dụng"); }
                      }
                return View(KH);

            }
            catch
            {
                return View();
            }
        }


        [HttpGet]
        public ActionResult Edit()
        {
            if (Session["User"] != null)
                ViewBag.User = Session["User"].ToString();
            if (Session["Email"] != null)
                ViewBag.Email = Session["Email"].ToString();
            var td = new KHACH_HANG_DAO().TimEmailKH(ViewBag.Email);

            return View(td);
        }

        // POST: KhachHang/Edit/5
        [HttpPost]
        public ActionResult Edit(KHACH_HANG model)
        {
            if (Session["User"] != null)
                ViewBag.User = Session["User"].ToString();
            if (Session["Email"] != null)
                ViewBag.Email = Session["Email"].ToString();
            if (ModelState.IsValid)
            {
                model.MATKHAU = Encryptor.MD5Hash(model.MATKHAU);
                model.CONFIRM_PASS = Encryptor.MD5Hash(model.CONFIRM_PASS);
                var dao = new KHACH_HANG_DAO();
                bool kq = dao.UpdateKhachHang(model);
                if (kq)
                {
                    ModelState.AddModelError("", "cập nhật thành công khách hàng");
                    //return RedirectToAction("Index", "ADKhachHang");
                }
                else
                {
                    ModelState.AddModelError("", "cập nhật thất bại khách hàng");
                }
            }
            return View(model);
        }

        // GET: KhachHang/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: KhachHang/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

NHAXE/NHAXE/NHAXE/Views/KhachHang/Create.cshtml
@model Models.Framework.KHACH_HANG
@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="format-detection" content="telephone=no" />
    <meta property="fb:admins" content="1373014969" />
    <meta property="fb:app_id" content="1677748725772019" />
    <title>Đăng ký | PONOBus ID</title>

    <!--[if lt IE 9]>
     <script src="html5.js" tppabs="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link rel="stylesheet" id="theme-style-css" href="/Content/css/style.min.css" type="text/css" media="all" />
    <!--  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script> -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />

</head>
<body style="background: #fff;">

    <section id="body-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 col-ms-12">
                    <div style="height: 272px;
    border-radius: 5px;border: 1px solid #ddd;height: 500px;">
                        <!-- Nav tabs -->
                        <div class="text-center text-uppercase text-primary">
                            <strong>Đăng kí Khách hàng</strong>
                        </div>
                        @using (Html.BeginForm("Create", "KhachHang", FormMethod.Post))
            {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal lb1">

                                @Html.ValidationSummary(true, "", new { @class = "text-danger err" })
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-ms-12">
                                    <div class="form-group">
                                        <label for="">Họ và tên*</label>
                                        <div class="col-md-12">

                                            @Html.TextBoxFor(model => model.TEN_KH, new { htmlAttributes = new { @class = "form-control", id = "tongtien" } })
                                            @Html.ValidationMessageFor(model => model.TEN_KH, "", new { @class = "text-danger err1" })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-ms-12">
                                    <div class="form-group">
                                        <label for="">Email*</label>
                                        <div class="col-md-12">

                                            @Html.TextBoxFor(model => model.EMAIL_KH, new { htmlAttributes = new { @class = "form-control", id = "tongtien" } })
                                            @Html.ValidationMessageFor(model => model.EMAIL_KH, "", new { @class = "text-danger err1" })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-ms-12">
                                    <div class="form-group">
                                        <label for="">Số điện thoại*</label>
                                        <div class="col-md-12">

                                            @Html.TextBoxFor(model => model.SDT_KH, new { htmlAttributes = new { @class = "form-control", id = "tongtien" } })
                                            @Html.ValidationMessageFor(model => model.SDT_KH, "", new { @class = "text-danger err1" })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-ms-12">
                                    <div class="form-group">
                                        <label for="">Số chứng minh thư*</label>
                                        <div class="col-md-12">

                                            @Html.TextBoxFor(model => model.CMND_KH, new { htmlAttributes = new { @class = "form-control", id = "tongtien" } })
                                            @Html.ValidationMessageFor(model => model.CMND_KH, "", new { @class = "text-danger err1" })
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-ms-12">
                                    <div class="form-group">
                                        <label for="">Địa chỉ khách hàng*</label>
                                        <div class="col-md-12">

                                            @Html.TextBoxFor(model => model.DIACHI_KH, new { htmlAttributes = new { @class = "form-control", id = "tongtien" } })
                                            @Html.ValidationMessageFor(model => model.DIACHI_KH, "", new { @class = "text-danger err1" })
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-ms-12">
                                    <div class="form-group">
                                        <label for="">Mật Khẩu*</label>
                                        <div class="col-md-12">

                                            @Html.PasswordFor(model => model.MATKHAU, new { htmlAttributes = new { @class = "form-control", id = "tongtien" } })
                                            @Html.ValidationMessageFor(model => model.MATKHAU, "", new { @class = "text-danger err1" })
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-ms-12">
                                    <div class="form-group">
                                        <label for="">Xác nhận mật khẩu*</label>
                                        <div class="col-md-12">

                                            @Html.PasswordFor(model => model.CONFIRM_PASS, new { htmlAttributes = new { @class = "form-control", id = "tongtien" } })
                                            @Html.ValidationMessageFor(model => model.CONFIRM_PASS, "", new { @class = "text-danger err1" })
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-4 col-md-10 btnm">
                                        <input type="submit" value="Đăng Kí" class="btn btn-primary" />
                                    </div>
                                </div>
                            </div>
                        }

                        

                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 col-ms-12">
                    <div class="panel" style="border: 1px solid #ddd;height: 500px;">
                        <p class="text-center text-uppercase text-primary">
                            <strong>Điều khoản &amp;Đăng kí</strong>
                        </p>
                        <div style="padding: 20px;">
                            <p class="text-justify">(*) Quý khách vui lòng đăng kí trước khi bắt đầu mua vé.</p>
                            <p class="text-justify">(*) Quý khách vui lòng điền chính xác thông tin để công ty liên hệ trong quá trình đưa đón khách</p>
                          
                            <p class="text-justify">
                                (*) Nếu quý khách có thắc mắc vấn đề gì, vui lòng liên hệ số điện thoại<br>
                                <strong class="text-primary" style="font-size: 1.2em;">1900 8198</strong>
                                
                            </p>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </section>
    
</body>
</html>

NHAXE/NHAXE/NHAXE/Views/KhachHang/Edit.cshtml
@model Models.Framework.KHACH_HANG

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Info | PONOBus ID</title>
</head>
<
<body style="background: #fff;">

    <section id="body-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-3"></div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 col-ms-12">
                    <div style="border-radius: 5px;border: 1px solid #ddd;height: 500px;">
                        <!-- Nav tabs -->
                        <div class="text-center text-uppercase text-primary" style="margin-bottom: 25px; margin-top:10px;">
                            <p class="text-center text-primary text-uppercase">
                                <strong style="font-size : 30px">sửa thông tin cá nhân</strong>
                            </p>
                            @using (Html.BeginForm("Edit", "KhachHang", FormMethod.Post))
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-horizontal" style="color: #333;">

                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                                    <div class="form-group them1">
                                        
                                        
                                        <div class="col-lg-4 col-md-4">
                                            <label for="">Email</label>

                                        </div>
                                        <div class="col-lg-8 col-md-8">
                                            <div class="on"></div>
                                            @Html.TextBoxFor(model => model.EMAIL_KH, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.EMAIL_KH, "", new { @class = "text-danger" })

                                        </div>
                                    </div>


                                  
                                        <div class="form-group">
                                            
                                            <div class="col-lg-4 col-md-4">
                                                <label for="">Họ và tên</label>

                                            </div>
                                            <div class="col-lg-8 col-md-8">
                                                @Html.TextBoxFor(model => model.TEN_KH, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.TEN_KH, "", new { @class = "text-danger" })

                                            </div>
                                        </div>
                                    
                                            <div class="form-group">
                                                <div class="col-lg-4 col-md-4">
                                                    <label for="">Số điện thoại</label>
                                                </div>
                                                <div class="col-lg-8 col-md-8">
                                                    @Html.TextBoxFor(model => model.SDT_KH, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.SDT_KH, "", new { @class = "text-danger" })

                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <div class="col-lg-4 col-md-4">
                                                    <label for="">Số CMND</label>
                                                </div>
                                                <div class="col-lg-8 col-md-8">
                                                   @Html.TextBoxFor(model => model.CMND_KH, new { htmlAttributes = new { @class = "form-control" } })
                                                   @Html.ValidationMessageFor(model => model.CMND_KH, "", new { @class = "text-danger" })

                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <div class="col-lg-4 col-md-4">
                                                    <label for="">Địa chỉ</label>
                                                </div>
                                                <div class="col-lg-8 col-md-8">
                                                    @Html.TextBoxFor(model => model.DIACHI_KH, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.DIACHI_KH, "", new { @class = "text-danger" })

                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <div class="col-lg-4 col-md-4">
                                                    <label for="">Mật khẩu</label>
                                                </div>
                                                <div class="col-lg-8 col-md-8">
                                                    @Html.PasswordFor(model => model.MATKHAU, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.MATKHAU, "", new { @class = "text-danger" })
                                                </div>
                                               
                                            </div>

                                            <div class="form-group">
                                                <div class="col-lg-4 col-md-4">
                                                    <label for="">Nhập lại mật khẩu</label>
                                                </div>
                                                <div class="col-lg-8 col-md-8">
                                                    @Html.PasswordFor(model => model.CONFIRM_PASS, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.CONFIRM_PASS, "", new { @class = "text-danger" })

                                                </div>
                                               

                                            </div>

                                            <div class="form-group">
                                                <div class="col-md-offset-4 col-md-10">
                                                    <input type="submit" value="Cập nhật" class="btn btn-primary" />
                                                </div>
                                            </div>
                                        </div>
                                        }
                                    </div>
                                </div>




                    <div class="col-lg-5 col-md-5 col-sm-6 col-xs-12 col-ms-12"></div>
                </div>
            </div>



        </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>



        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

        <script type="text/javascript" src="Content/js/SalsaCalendar.min.js"></script>



    </section>
</body>
</html>